services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  doctors_service:
    image: doctors_service
    build:
      context: doctors_service/.
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"

volumes:
  pgdata:
    driver: local # хранить на диске(в локальном хранилище)