services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      # pg_isready уже есть внутри официального образа postgres
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres || exit 1"]
      interval: 5s       # как часто проверять
      timeout: 3s        # таймаут одной проверки
      retries: 10        # сколько раз попробовать
      start_period: 5s   # дать время на холодный старт
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./init:/docker-entrypoint-initdb.d

  doctors_service:
    image: doctors_service
    build:
      context: .                                  
      dockerfile: ./doctors_service/Dockerfile
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
    driver: local # хранить на диске(в локальном хранилище)