package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/Quszlet/gateway_service/graph/model"
	JSON "github.com/Quszlet/libs/json"
)

// CreateDoctor is the resolver for the createDoctor field.
func (r *mutationResolver) CreateDoctor(ctx context.Context, input model.NewDoctor) (*model.Doctor, error) {
	base := r.DoctorsURL
	if base == "" {
		return nil, fmt.Errorf("doctors service url is not configured")
	}

	url := fmt.Sprintf("%s/doctor", strings.TrimSuffix(base, "/"))

	body, err := json.Marshal(input)
	if err != nil {
		return nil, fmt.Errorf("error marshal: %w", err)
	}

	resp, err := http.Post(url, "application/json", bytes.NewBuffer(body))
	if err != nil {
		fmt.Println("Ошибка запроса:", err)
		return &model.Doctor{}, err
	}
	defer resp.Body.Close()

	message := ""
	if err := JSON.ParseResp(resp, &message); err != nil {
		return nil, fmt.Errorf("doctor decode failed: %w", err)
	}

	var id int
	if _, err := fmt.Sscanf(message, "User created with id %d", &id); err != nil {
		return nil, fmt.Errorf("failed to parse created doctor id: %w", err)
	}

	getURL := fmt.Sprintf("%s/doctor/%d", strings.TrimSuffix(base, "/"), id)
	getResp, err := http.Get(getURL)
	if err != nil {
		return nil, fmt.Errorf("doctor request failed: %w", err)
	}
	defer getResp.Body.Close()

	doctor := model.Doctor{}
	if err := JSON.ParseResp(getResp, &doctor); err != nil {
		return nil, fmt.Errorf("doctor decode failed: %w", err)
	}

	return &doctor, nil
}

// DeleteDoctor is the resolver for the deleteDoctor field.
func (r *mutationResolver) DeleteDoctor(ctx context.Context, input model.DeleteDoctor) (*model.Response, error) {
	base := r.DoctorsURL
	if base == "" {
		return nil, fmt.Errorf("doctors service url is not configured")
	}

	url := fmt.Sprintf("%s/doctor/delete/%d", strings.TrimSuffix(base, "/"), input.ID)
	req, _ := http.NewRequest("DELETE", url, bytes.NewBuffer([]byte{}))
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("timeSlots request failed: %w", err)
	}
	defer resp.Body.Close()

	result := model.Response{}

	rawBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %w", err)
	}

	payload := map[string]any{}
	if err := json.Unmarshal(rawBody, &payload); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	if msg, ok := payload["message"].(string); ok {
		result.Message = msg
	}

	return &result, nil
}

// Doctor is the resolver for the doctor field.
func (r *queryResolver) Doctor(ctx context.Context, id int32) (*model.Doctor, error) {
	base := r.DoctorsURL
	if base == "" {
		return nil, fmt.Errorf("doctors service url is not configured")
	}

	url := fmt.Sprintf("%s/doctor/%d", strings.TrimSuffix(base, "/"), id)
	resp, err := http.Get(url)
	if err != nil {
		return nil, fmt.Errorf("doctor request failed: %w", err)
	}
	defer resp.Body.Close()

	doctor := model.Doctor{}
	if err := JSON.ParseResp(resp, &doctor); err != nil {
		return nil, fmt.Errorf("doctor decode failed: %w", err)
	}

	return &doctor, nil
}

// Schedule is the resolver for the schedule field.
func (r *queryResolver) Schedule(ctx context.Context, doctorID int32, date time.Time) ([]*model.TimeSlot, error) {
	base := r.ScheduleURL
	if base == "" {
		return nil, fmt.Errorf("doctors service url is not configured")
	}

	url := fmt.Sprintf("%s/schedule", strings.TrimSuffix(base, "/"))

	jsonBody := map[string]any{
		"doctor_id": doctorID,
		"date":      date,
	}
	body, err := json.Marshal(jsonBody)
	if err != nil {
		return nil, fmt.Errorf("error marshal: %w", err)
	}
	bodyD := bytes.NewBuffer(body)
	req, _ := http.NewRequest("GET", url, bodyD)

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("timeSlots request failed: %w", err)
	}
	defer resp.Body.Close()

	timeSlots := []*model.TimeSlot{}
	if err := JSON.ParseResp(resp, &timeSlots); err != nil {
		return nil, fmt.Errorf("timeSlots decode failed: %w", err)
	}

	return timeSlots, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
