events {}

http {
    upstream doctors_service {

        server doctors_service-1:8080;
        server doctors_service-2:8080;
        server doctors_service-3:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://doctors_service;
        }
    }
}