// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type DeleteDoctor struct {
	ID int32 `json:"id"`
}

type Doctor struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Surname      string `json:"surname"`
	Patronymic   string `json:"patronymic"`
	Specialty    string `json:"specialty"`
	Clinic       string `json:"clinic"`
	StatusActive bool   `json:"status_active"`
}

type Mutation struct {
}

type NewDoctor struct {
	Name         string `json:"name"`
	Surname      string `json:"surname"`
	Patronymic   string `json:"patronymic"`
	Specialty    string `json:"specialty"`
	Clinic       string `json:"clinic"`
	StatusActive bool   `json:"status_active"`
}

type Query struct {
}

type Response struct {
	Message string `json:"message"`
}

type TimeSlot struct {
	ID          int32     `json:"id"`
	DoctorID    int32     `json:"doctor_id"`
	Date        time.Time `json:"date"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
	IsAvailable bool      `json:"is_available"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
